/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AFX/CGMotion 3DModel Maker (https://sketchfab.com/afx_cgmotion)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-street-at-night-fb1bdcd71a5544d699379d2d13dd1171
Title: Japanese street at night
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/japan_street.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Props_10}
        position={[1.548, 0.082, 1.603]}
      />
      <pointLight color="hotpink"position={[1.548, 1.082, 1.603]} intensity={3}/>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Props_10}
        position={[1.481, 0.082, 0.541]}
      />
    <pointLight castShadow color="hotpink"position={[1.081, 1.082, 0.541]} intensity={3}/>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Props_10}
        position={[1.281, 0.029, 2.036]}
        rotation={[Math.PI, -1.531, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Props_10}
        position={[1.217, 0.029, 1.038]}
        rotation={[Math.PI, -1.387, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.Props_01}
        position={[-1.039, 0.092, -0.205]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.Props_02}
        position={[-1.246, 1.12, -0.197]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.Props_06}
        position={[-0.986, 0, 0.44]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.Props_03}
        position={[-1.249, 1.417, 0.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.Props_05}
        position={[-1.255, 1.862, 0.048]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.Props_05}
        position={[-1.222, 2.289, -0.194]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.Build_A_1}
        position={[-2.543, 0, 0.578]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.Build_2}
        position={[-1.012, 3.137, 0.481]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials.Props_09}
        position={[-0.256, 0.15, -0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.Build_A_2}
        position={[-1.202, 2.308, 1.781]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.Props_09}
        position={[-1.201, 1.066, -0.458]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.Build_1}
        position={[-2.543, 0, 0.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.Build_A_2}
        position={[-1.234, 1.655, -0.437]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.Build_2}
        position={[-1.093, 2.518, 0.649]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials.Props_08}
        position={[-0.936, 3.161, -0.574]}
      />
      <pointLight castShadow color="blue"position={[-0.536, 3.161, -0.474]} intensity={3}/>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials.Props_09}
        position={[-1.255, 2.213, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.Props_03}
        position={[-0.984, 0, -2.089]}
        rotation={[Math.PI, -1.358, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.Props_05}
        position={[-1.275, 2.873, -0.946]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials.Props_05}
        position={[-1.25, 3.193, -0.977]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        material={materials.Props_05}
        position={[-1.302, 4.039, -3.116]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_52.geometry}
        material={materials.Props_01}
        position={[-1.746, 0.092, -3.703]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        material={materials.Props_02}
        position={[-1.899, 1.345, -3.573]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_56.geometry}
        material={materials.Props_02}
        position={[-1.82, 0.718, -3.548]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_58.geometry}
        material={materials.Props_06}
        position={[-2.524, 0, -3.756]}
        rotation={[0, 0.048, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials.Props_06}
        position={[-2.524, 0.36, -3.756]}
        rotation={[-Math.PI, -0.014, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials.Props_06}
        position={[-2.566, 0.721, -3.772]}
        rotation={[0, 0.102, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_64.geometry}
        material={materials.Props_06}
        position={[-1.051, 0, -2.854]}
        rotation={[0, 0.049, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_66.geometry}
        material={materials.Build_3}
        position={[-2.283, 0, -2.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials.Build_B_1}
        position={[-2.283, 0, -2.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        material={materials.Build_3}
        position={[-1.218, 4.262, -1.934]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_72.geometry}
        material={materials.Props_09}
        position={[-1.24, 0.002, -2.321]}
        rotation={[0, 0, 0.018]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_74.geometry}
        material={materials.Build_1}
        position={[-2.283, 0, -2.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_76.geometry}
        material={materials.Props_09}
        position={[-1.275, 2.053, -1.412]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_78.geometry}
        material={materials.Build_B_2}
        position={[-1.501, 2.892, -1.882]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials.Props_08}
        position={[-0.806, 2.894, -3.087]}
        rotation={[0, 0, -0.044]}
      />
      <pointLight color="white"position={[-0.806, 2.894, -3.087]} intensity={1}/>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        material={materials.Build_B_2}
        position={[-1.076, 4.451, -3.386]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_84.geometry}
        material={materials.Props_05}
        position={[-0.998, 0.799, -1.867]}
        rotation={[-2.461, 0.205, 2.978]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_86.geometry}
        material={materials.Build_C_2}
        position={[-1.11, 2.308, -6.284]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_88.geometry}
        material={materials.Build_C_1}
        position={[-2.152, 0, -5.263]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_90.geometry}
        material={materials.Build_3}
        position={[-1.033, 2.146, -5.695]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_92.geometry}
        material={materials.Props_07}
        position={[-0.915, 0.36, -4.661]}
        rotation={[0, 0.017, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_94.geometry}
        material={materials.Props_01}
        position={[-0.904, 0.05, -4.645]}
        rotation={[0, 1.538, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_96.geometry}
        material={materials.Props_07}
        position={[-0.89, 0.722, -4.627]}
        rotation={[0, -0.206, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_98.geometry}
        material={materials.Props_01}
        position={[-0.947, 2.222, -4.615]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_100.geometry}
        material={materials.Props_05}
        position={[-1.122, 2.561, -6.033]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_102.geometry}
        material={materials.Props_02}
        position={[-1.514, 1.12, -4.156]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_104.geometry}
        material={materials.Props_09}
        position={[-1.099, 1.298, -4.539]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_106.geometry}
        material={materials.Build_1}
        position={[-2.152, 0, -5.263]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_108.geometry}
        material={materials.Build_C_2}
        position={[-1.107, 3.147, -5.118]}
        rotation={[-Math.PI / 2, 1.484, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_110.geometry}
        material={materials.Props_08}
        position={[-0.834, 3.679, -6.113]}
        rotation={[0, 0, -0.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_112.geometry}
        material={materials.Props_03}
        position={[-0.951, 0, -8.744]}
        rotation={[0, 0.183, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_114.geometry}
        material={materials.Props_01}
        position={[-1.061, 2.426, -7.435]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_116.geometry}
        material={materials.Props_05}
        position={[-1.234, 2.909, -8.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_118.geometry}
        material={materials.Props_05}
        position={[-1.027, 4.181, -8.993]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_120.geometry}
        material={materials.Build_1}
        position={[-2.55, 0, -7.595]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_122.geometry}
        material={materials.Build_1}
        position={[-2.256, 0, -8.601]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_124.geometry}
        material={materials.Build_D_2}
        position={[-1.225, 3.175, -7.564]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_126.geometry}
        material={materials.Build_D_1}
        position={[-2.265, 0, -7.794]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_128.geometry}
        material={materials.Build_3}
        position={[-1.08, 2.249, -7.492]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_130.geometry}
        material={materials.Build_D_2}
        position={[-1.14, 3.852, -8.239]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_132.geometry}
        material={materials.Props_09}
        position={[-1.214, 0.89, -9.131]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_134.geometry}
        material={materials.Props_09}
        position={[-1.254, 1.952, -8.604]}
        rotation={[Math.PI, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_136.geometry}
        material={materials.Props_08}
        position={[-0.947, 2.97, -6.72]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <pointLight color="purple"position={[-0.947, 2.97, -6.72]} intensity={3}/>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_138.geometry}
        material={materials.Build_E}
        position={[3.248, 0, 1.024]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_140.geometry}
        material={materials.Props_01}
        position={[2.05, 2.48, 0.418]}
        rotation={[Math.PI, 0, 3.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_142.geometry}
        material={materials.Props_05}
        position={[2.214, 4.042, 1.636]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_144.geometry}
        material={materials.Build_E}
        position={[2.184, 2.808, 1.27]}
        rotation={[Math.PI, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_146.geometry}
        material={materials.Props_09}
        position={[2.193, 2.807, 1.688]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_148.geometry}
        material={materials.Build_4}
        position={[2.284, 0, -1.426]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_150.geometry}
        material={materials.Build_F_2}
        position={[2.284, 0, -1.426]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_152.geometry}
        material={materials.Build_F_2}
        position={[3.207, 0, -0.916]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_154.geometry}
        material={materials.Props_02}
        position={[1.21, 1.328, -1.535]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_156.geometry}
        material={materials.Props_02}
        position={[1.214, 1.191, -1.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_158.geometry}
        material={materials.Props_03}
        position={[1.656, 1.349, -1.317]}
        rotation={[0.038, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_160.geometry}
        material={materials.Props_01}
        position={[1.044, 2.222, -2.162]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_162.geometry}
        material={materials.Props_05}
        position={[1.566, 3.214, -0.191]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_164.geometry}
        material={materials.Props_05}
        position={[1.41, 3.779, -0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_166.geometry}
        material={materials.Props_05}
        position={[1.824, 4.414, -0.181]}
        scale={0.765}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_168.geometry}
        material={materials.Build_F_2}
        position={[0.929, 4.752, -1.497]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_170.geometry}
        material={materials.Props_08}
        position={[0.824, 3.557, -0.405]}
        rotation={[0, 0, 0.009]}
      />
      <pointLight color="white"position={[0.824, 3.557, -0.405]} intensity={1}/>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_172.geometry}
        material={materials.Props_09}
        position={[1.415, 3.917, -0.311]}
        rotation={[-0.163, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_174.geometry}
        material={materials.Build_F_2}
        position={[1.317, 3.141, -0.82]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_176.geometry}
        material={materials.Props_09}
        position={[1.238, 2.043, -2.479]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_178.geometry}
        material={materials.Build_F_1}
        position={[2.284, 0, -1.426]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_180.geometry}
        material={materials.Build_A_2}
        position={[2.13, 1.558, -1.322]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_182.geometry}
        material={materials.Props_05}
        position={[1.659, 1.766, -1.343]}
        rotation={[Math.PI / 2, -Math.PI / 3, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_184.geometry}
        material={materials.Build_1}
        position={[1.204, 0.908, -2.418]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_186.geometry}
        material={materials.Build_G_1}
        position={[2.269, 0, -3.854]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_188.geometry}
        material={materials.Props_01}
        position={[1.036, 0.1, -4.375]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_190.geometry}
        material={materials.Props_01}
        position={[1.044, 0.05, -4.398]}
        rotation={[0, 1.556, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_192.geometry}
        material={materials.Props_06}
        position={[1.023, 0.664, -4.343]}
        rotation={[0, 0.065, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_194.geometry}
        material={materials.Props_07}
        position={[0.981, 0.103, -4.91]}
        rotation={[-Math.PI, 1.331, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_196.geometry}
        material={materials.Props_04}
        position={[1.113, 1.971, -3.4]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_198.geometry}
        material={materials.Props_03}
        position={[1.228, 1.422, -4.267]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_200.geometry}
        material={materials.Props_04}
        position={[0.996, 1.903, -4.219]}
      />
      <pointLight color="orange"position={[0.996, 1.903, -4.219]} intensity={1}/>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_202.geometry}
        material={materials.Build_1}
        position={[2.559, 0, -2.828]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_204.geometry}
        material={materials.Build_G_2}
        position={[1.045, 2.513, -3.044]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_206.geometry}
        material={materials.Build_4}
        position={[1.262, 2.412, -3.849]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_208.geometry}
        material={materials.Props_08}
        position={[0.952, 3.091, -2.997]}
      />
      <pointLight color="red"position={[0.952, 3.091, -2.997]} intensity={3}/>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_210.geometry}
        material={materials.Build_4}
        position={[1.123, 4.122, -3.862]}
        rotation={[0, 0, 0.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_212.geometry}
        material={materials.Props_05}
        position={[1.239, 2.252, -3.07]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_214.geometry}
        material={materials.Build_H_1}
        position={[2.324, 0, -6.135]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_216.geometry}
        material={materials.Props_03}
        position={[0.99, 0, -5.638]}
        rotation={[Math.PI, -1.455, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_218.geometry}
        material={materials.Props_02}
        position={[1.227, 1.345, -5.275]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_220.geometry}
        material={materials.Props_02}
        position={[1.253, 0.718, -5.354]}
        rotation={[-3.118, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_222.geometry}
        material={materials.Props_02}
        position={[1.312, 1.12, -5.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_224.geometry}
        material={materials.Props_05}
        position={[0.979, 2.016, -6.669]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_226.geometry}
        material={materials.Props_05}
        position={[1.292, 3, -6.955]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_228.geometry}
        material={materials.Props_05}
        position={[1.477, 4.753, -5.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_230.geometry}
        material={materials.Props_09}
        position={[1.263, 1.475, -5.696]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_232.geometry}
        material={materials.Build_1}
        position={[1.988, 0, -7.144]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_234.geometry}
        material={materials.Build_H_2}
        position={[1.321, 2.597, -6.387]}
        rotation={[2.551, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_236.geometry}
        material={materials.Props_08}
        position={[0.949, 2.165, -5.184]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <pointLight color="blue"position={[0.949, 2.165, -5.184]} intensity={3}/>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_238.geometry}
        material={materials.Props_08}
        position={[0.955, 3.919, -7.13]}
        rotation={[0, 0, 0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_240.geometry}
        material={materials.Build_4}
        position={[1.204, 3.264, -5.46]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_242.geometry}
        material={materials.Props_09}
        position={[1.312, 1.952, -5.872]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_244.geometry}
        material={materials.Build_I}
        position={[-1.244, 0, -11.397]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_246.geometry}
        material={materials.Props_02}
        position={[-1.74, 1.12, -10.425]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_248.geometry}
        material={materials.Props_07}
        position={[-2.427, 0.259, -10.205]}
        rotation={[0, -1.555, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_250.geometry}
        material={materials.Props_06}
        position={[-3.132, -0.001, -9.854]}
        rotation={[0, 0.001, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_252.geometry}
        material={materials.Props_05}
        position={[-1.439, 4.384, -10.378]}
        scale={0.765}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_254.geometry}
        material={materials.Build_I}
        position={[-1.554, 2.649, -10.41]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_256.geometry}
        material={materials.Build_F_2}
        position={[-0.396, 3.141, -10.503]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_258.geometry}
        material={materials.Props_01}
        position={[-1.738, 2.222, -10.231]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_260.geometry}
        material={materials.Build_1}
        position={[-1.155, 0.908, -10.403]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_262.geometry}
        material={materials.Build_J}
        position={[2.782, 0, -11.402]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_264.geometry}
        material={materials.Build_2}
        position={[2.042, 5.157, -10.243]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_266.geometry}
        material={materials.Build_1}
        position={[1.286, 0.949, -10.266]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_268.geometry}
        material={materials.Props_05}
        position={[0.794, 2.647, -10.417]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_270.geometry}
        material={materials.Build_J}
        position={[0.941, 2.606, -10.422]}
        rotation={[-Math.PI / 2, 0.536, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_272.geometry}
        material={materials.Props_02}
        position={[3.384, 1.345, -10.347]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_274.geometry}
        material={materials.Props_02}
        position={[3.305, 0.718, -10.373]}
        rotation={[-Math.PI / 2, -1.547, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_276.geometry}
        material={materials.Props_02}
        position={[2.319, 1.12, -10.432]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_278.geometry}
        material={materials.Props_09}
        position={[2.642, 0.89, -10.389]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_280.geometry}
        material={materials.Build_J}
        position={[2.186, 2.491, -10.464]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_282.geometry}
        material={materials.Props_09}
        position={[2.186, 2.491, -10.464]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_284.geometry}
        material={materials.Props_06}
        position={[2.651, 0, -10.235]}
        rotation={[0, -1.484, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_286.geometry}
        material={materials.pole}
        position={[0, 3.079, -0.293]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_288.geometry}
        material={materials.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_290.geometry}
        material={materials.ground}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_292.geometry}
        material={materials.pole}
        position={[0.213, 0, -9.96]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_294.geometry}
        material={materials.pole}
        position={[0.213, 8.167, -9.739]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_296.geometry}
        material={materials.pole}
        position={[0.075, 0, -9.96]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_298.geometry}
        material={materials.pole}
        position={[0.211, 3.641, -9.299]}
        rotation={[-0.16, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_300.geometry}
        material={materials.pole}
      />
    </group>
  )
}

useGLTF.preload('/assets/japan_street.glb')
export default Model;
